# Form implementation generated from reading ui file 'src/eric7/Plugins/VcsPlugins/vcsMercurial/QueuesExtension/HgQueuesNewPatchDialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HgQueuesNewPatchDialog(object):
    def setupUi(self, HgQueuesNewPatchDialog):
        HgQueuesNewPatchDialog.setObjectName("HgQueuesNewPatchDialog")
        HgQueuesNewPatchDialog.resize(400, 362)
        HgQueuesNewPatchDialog.setSizeGripEnabled(True)
        self.gridLayout_3 = QtWidgets.QGridLayout(HgQueuesNewPatchDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.nameLabel = QtWidgets.QLabel(parent=HgQueuesNewPatchDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_3.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(parent=HgQueuesNewPatchDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout_3.addWidget(self.nameEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=HgQueuesNewPatchDialog)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.messageEdit = EricSpellCheckedPlainTextEdit(parent=HgQueuesNewPatchDialog)
        self.messageEdit.setTabChangesFocus(True)
        self.messageEdit.setObjectName("messageEdit")
        self.gridLayout_3.addWidget(self.messageEdit, 1, 1, 1, 1)
        self.userGroup = QtWidgets.QGroupBox(parent=HgQueuesNewPatchDialog)
        self.userGroup.setCheckable(True)
        self.userGroup.setChecked(False)
        self.userGroup.setObjectName("userGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.userGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.currentUserCheckBox = QtWidgets.QCheckBox(parent=self.userGroup)
        self.currentUserCheckBox.setObjectName("currentUserCheckBox")
        self.gridLayout.addWidget(self.currentUserCheckBox, 0, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(parent=self.userGroup)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.userEdit = QtWidgets.QLineEdit(parent=self.userGroup)
        self.userEdit.setObjectName("userEdit")
        self.gridLayout.addWidget(self.userEdit, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.userGroup, 2, 0, 1, 2)
        self.dateGroup = QtWidgets.QGroupBox(parent=HgQueuesNewPatchDialog)
        self.dateGroup.setCheckable(True)
        self.dateGroup.setChecked(False)
        self.dateGroup.setObjectName("dateGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dateGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.currentDateCheckBox = QtWidgets.QCheckBox(parent=self.dateGroup)
        self.currentDateCheckBox.setObjectName("currentDateCheckBox")
        self.gridLayout_2.addWidget(self.currentDateCheckBox, 0, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(parent=self.dateGroup)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.dateGroup)
        self.dateTimeEdit.setDisplayFormat("yyyy-MM-dd hh:mm")
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_2.addWidget(self.dateTimeEdit, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(241, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.dateGroup, 3, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=HgQueuesNewPatchDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 4, 0, 1, 2)

        self.retranslateUi(HgQueuesNewPatchDialog)
        self.buttonBox.accepted.connect(HgQueuesNewPatchDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(HgQueuesNewPatchDialog.reject) # type: ignore
        self.currentUserCheckBox.toggled['bool'].connect(self.userEdit.setDisabled) # type: ignore
        self.currentUserCheckBox.toggled['bool'].connect(self.label_3.setDisabled) # type: ignore
        self.currentDateCheckBox.toggled['bool'].connect(self.label_4.setDisabled) # type: ignore
        self.currentDateCheckBox.toggled['bool'].connect(self.dateTimeEdit.setDisabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(HgQueuesNewPatchDialog)
        HgQueuesNewPatchDialog.setTabOrder(self.nameEdit, self.messageEdit)
        HgQueuesNewPatchDialog.setTabOrder(self.messageEdit, self.userGroup)
        HgQueuesNewPatchDialog.setTabOrder(self.userGroup, self.currentUserCheckBox)
        HgQueuesNewPatchDialog.setTabOrder(self.currentUserCheckBox, self.userEdit)
        HgQueuesNewPatchDialog.setTabOrder(self.userEdit, self.dateGroup)
        HgQueuesNewPatchDialog.setTabOrder(self.dateGroup, self.currentDateCheckBox)
        HgQueuesNewPatchDialog.setTabOrder(self.currentDateCheckBox, self.dateTimeEdit)
        HgQueuesNewPatchDialog.setTabOrder(self.dateTimeEdit, self.buttonBox)

    def retranslateUi(self, HgQueuesNewPatchDialog):
        _translate = QtCore.QCoreApplication.translate
        HgQueuesNewPatchDialog.setWindowTitle(_translate("HgQueuesNewPatchDialog", "New Patch"))
        self.nameLabel.setText(_translate("HgQueuesNewPatchDialog", "Name:"))
        self.nameEdit.setToolTip(_translate("HgQueuesNewPatchDialog", "Enter the patch name"))
        self.label_2.setText(_translate("HgQueuesNewPatchDialog", "Message:"))
        self.messageEdit.setToolTip(_translate("HgQueuesNewPatchDialog", "Enter the commit message for the patch"))
        self.userGroup.setToolTip(_translate("HgQueuesNewPatchDialog", "Select to give user information"))
        self.userGroup.setTitle(_translate("HgQueuesNewPatchDialog", "User"))
        self.currentUserCheckBox.setToolTip(_translate("HgQueuesNewPatchDialog", "Select to use the name of the current user"))
        self.currentUserCheckBox.setText(_translate("HgQueuesNewPatchDialog", "Use current user"))
        self.label_3.setText(_translate("HgQueuesNewPatchDialog", "Username:"))
        self.userEdit.setToolTip(_translate("HgQueuesNewPatchDialog", "Enter the user name to be used for the patch"))
        self.dateGroup.setToolTip(_translate("HgQueuesNewPatchDialog", "Select to give date and time information"))
        self.dateGroup.setTitle(_translate("HgQueuesNewPatchDialog", "Date and Time"))
        self.currentDateCheckBox.setToolTip(_translate("HgQueuesNewPatchDialog", "Select to use the current date and time"))
        self.currentDateCheckBox.setText(_translate("HgQueuesNewPatchDialog", "Use current date and time"))
        self.label_4.setText(_translate("HgQueuesNewPatchDialog", "Date/Time:"))
        self.dateTimeEdit.setToolTip(_translate("HgQueuesNewPatchDialog", "Enter the date and time to be used for the patch"))
from eric7.EricWidgets.EricSpellCheckedTextEdit import EricSpellCheckedPlainTextEdit
