# Form implementation generated from reading ui file 'src/eric7/WebBrowser/Network/SslErrorExceptionsDialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SslErrorExceptionsDialog(object):
    def setupUi(self, SslErrorExceptionsDialog):
        SslErrorExceptionsDialog.setObjectName("SslErrorExceptionsDialog")
        SslErrorExceptionsDialog.resize(751, 513)
        SslErrorExceptionsDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(SslErrorExceptionsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.errorsTree = QtWidgets.QTreeWidget(parent=SslErrorExceptionsDialog)
        self.errorsTree.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.errorsTree.setAlternatingRowColors(True)
        self.errorsTree.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.errorsTree.setAllColumnsShowFocus(True)
        self.errorsTree.setObjectName("errorsTree")
        self.gridLayout.addWidget(self.errorsTree, 0, 0, 3, 1)
        self.removeButton = QtWidgets.QPushButton(parent=SslErrorExceptionsDialog)
        self.removeButton.setObjectName("removeButton")
        self.gridLayout.addWidget(self.removeButton, 0, 1, 1, 1)
        self.removeAllButton = QtWidgets.QPushButton(parent=SslErrorExceptionsDialog)
        self.removeAllButton.setObjectName("removeAllButton")
        self.gridLayout.addWidget(self.removeAllButton, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 128, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SslErrorExceptionsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SslErrorExceptionsDialog)
        self.buttonBox.accepted.connect(SslErrorExceptionsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SslErrorExceptionsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SslErrorExceptionsDialog)

    def retranslateUi(self, SslErrorExceptionsDialog):
        _translate = QtCore.QCoreApplication.translate
        SslErrorExceptionsDialog.setWindowTitle(_translate("SslErrorExceptionsDialog", "SSL Error Exceptions"))
        self.errorsTree.setSortingEnabled(True)
        self.errorsTree.headerItem().setText(0, _translate("SslErrorExceptionsDialog", "Code"))
        self.errorsTree.headerItem().setText(1, _translate("SslErrorExceptionsDialog", "Error Description"))
        self.removeButton.setToolTip(_translate("SslErrorExceptionsDialog", "Press to remove the selected entries"))
        self.removeButton.setText(_translate("SslErrorExceptionsDialog", "&Remove"))
        self.removeAllButton.setToolTip(_translate("SslErrorExceptionsDialog", "Press to remove all entries"))
        self.removeAllButton.setText(_translate("SslErrorExceptionsDialog", "Remove &All"))
