# Form implementation generated from reading ui file 'src/eric7/MicroPython/EthernetDialogs/HostnameDialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HostnameDialog(object):
    def setupUi(self, HostnameDialog):
        HostnameDialog.setObjectName("HostnameDialog")
        HostnameDialog.resize(400, 78)
        HostnameDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(HostnameDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(parent=HostnameDialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.hostnameEdit = EricHostnameInputWidget(parent=HostnameDialog)
        self.hostnameEdit.setObjectName("hostnameEdit")
        self.horizontalLayout_2.addWidget(self.hostnameEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=HostnameDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(HostnameDialog)
        self.buttonBox.accepted.connect(HostnameDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(HostnameDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(HostnameDialog)

    def retranslateUi(self, HostnameDialog):
        _translate = QtCore.QCoreApplication.translate
        HostnameDialog.setWindowTitle(_translate("HostnameDialog", "Host Name"))
        self.label_5.setText(_translate("HostnameDialog", "Hostname:"))
        self.hostnameEdit.setToolTip(_translate("HostnameDialog", "Enter the host name for the device (leave empty for MicroPython &lt; 1.20)."))
from eric7.EricNetwork.EricHostnameInputWidget import EricHostnameInputWidget
