# Form implementation generated from reading ui file 'src/eric7/Plugins/VcsPlugins/vcsMercurial/UncommitExtension/HgUncommitDialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HgUncommitDialog(object):
    def setupUi(self, HgUncommitDialog):
        HgUncommitDialog.setObjectName("HgUncommitDialog")
        HgUncommitDialog.resize(450, 500)
        HgUncommitDialog.setSizeGripEnabled(True)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(HgUncommitDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logGroup = QtWidgets.QGroupBox(parent=HgUncommitDialog)
        self.logGroup.setObjectName("logGroup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.logGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logEdit = EricSpellCheckedTextEdit(parent=self.logGroup)
        self.logEdit.setTabChangesFocus(True)
        self.logEdit.setAcceptRichText(False)
        self.logEdit.setObjectName("logEdit")
        self.verticalLayout.addWidget(self.logEdit)
        self.label = QtWidgets.QLabel(parent=self.logGroup)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.recentComboBox = QtWidgets.QComboBox(parent=self.logGroup)
        self.recentComboBox.setObjectName("recentComboBox")
        self.verticalLayout.addWidget(self.recentComboBox)
        self.verticalLayout_3.addWidget(self.logGroup)
        self.keepCheckBox = QtWidgets.QCheckBox(parent=HgUncommitDialog)
        self.keepCheckBox.setObjectName("keepCheckBox")
        self.verticalLayout_3.addWidget(self.keepCheckBox)
        self.allowDirtyCheckBox = QtWidgets.QCheckBox(parent=HgUncommitDialog)
        self.allowDirtyCheckBox.setObjectName("allowDirtyCheckBox")
        self.verticalLayout_3.addWidget(self.allowDirtyCheckBox)
        self.groupBox = QtWidgets.QGroupBox(parent=HgUncommitDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.authorComboBox = QtWidgets.QComboBox(parent=self.groupBox)
        self.authorComboBox.setEditable(True)
        self.authorComboBox.setObjectName("authorComboBox")
        self.verticalLayout_2.addWidget(self.authorComboBox)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.dateTimeGroup = QtWidgets.QGroupBox(parent=HgUncommitDialog)
        self.dateTimeGroup.setCheckable(True)
        self.dateTimeGroup.setChecked(False)
        self.dateTimeGroup.setObjectName("dateTimeGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dateTimeGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(241, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.dateTimeGroup)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.dateTimeGroup)
        self.dateTimeEdit.setDisplayFormat("yyyy-MM-dd hh:mm")
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_2.addWidget(self.dateTimeEdit, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.dateTimeGroup)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=HgUncommitDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(HgUncommitDialog)
        self.buttonBox.accepted.connect(HgUncommitDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(HgUncommitDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(HgUncommitDialog)
        HgUncommitDialog.setTabOrder(self.logEdit, self.recentComboBox)
        HgUncommitDialog.setTabOrder(self.recentComboBox, self.keepCheckBox)
        HgUncommitDialog.setTabOrder(self.keepCheckBox, self.allowDirtyCheckBox)
        HgUncommitDialog.setTabOrder(self.allowDirtyCheckBox, self.authorComboBox)
        HgUncommitDialog.setTabOrder(self.authorComboBox, self.dateTimeGroup)
        HgUncommitDialog.setTabOrder(self.dateTimeGroup, self.dateTimeEdit)

    def retranslateUi(self, HgUncommitDialog):
        _translate = QtCore.QCoreApplication.translate
        HgUncommitDialog.setWindowTitle(_translate("HgUncommitDialog", "Undo Local Commit"))
        self.logGroup.setTitle(_translate("HgUncommitDialog", "Commit Message"))
        self.logEdit.setToolTip(_translate("HgUncommitDialog", "Enter the log message."))
        self.logEdit.setWhatsThis(_translate("HgUncommitDialog", "<b>Log Message</b>\n"
"<p>Enter the log message for the uncommit action.</p>"))
        self.label.setText(_translate("HgUncommitDialog", "Recent commit messages"))
        self.recentComboBox.setToolTip(_translate("HgUncommitDialog", "Select a recent commit message to use"))
        self.keepCheckBox.setToolTip(_translate("HgUncommitDialog", "Select to allow an empty commit after undoing it."))
        self.keepCheckBox.setText(_translate("HgUncommitDialog", "Allow empty commit after undoing commit"))
        self.allowDirtyCheckBox.setToolTip(_translate("HgUncommitDialog", "Select to allow undoing the commit with outstanding changes."))
        self.allowDirtyCheckBox.setText(_translate("HgUncommitDialog", "Allow undoing commit with outstanding changes"))
        self.groupBox.setTitle(_translate("HgUncommitDialog", "Author"))
        self.label_3.setText(_translate("HgUncommitDialog", "Enter author name to override the configured user:"))
        self.authorComboBox.setToolTip(_translate("HgUncommitDialog", "Enter an author name in order to override the configured one"))
        self.dateTimeGroup.setToolTip(_translate("HgUncommitDialog", "Select to give date and time information"))
        self.dateTimeGroup.setTitle(_translate("HgUncommitDialog", "Date and Time"))
        self.label_4.setText(_translate("HgUncommitDialog", "Date/Time:"))
        self.dateTimeEdit.setToolTip(_translate("HgUncommitDialog", "Enter the date and time to be used"))
from eric7.EricWidgets.EricSpellCheckedTextEdit import EricSpellCheckedTextEdit
