# Form implementation generated from reading ui file 'src/eric7/QScintilla/ZoomDialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ZoomDialog(object):
    def setupUi(self, ZoomDialog):
        ZoomDialog.setObjectName("ZoomDialog")
        ZoomDialog.resize(206, 77)
        self.vboxlayout = QtWidgets.QVBoxLayout(ZoomDialog)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.zoomLabel = QtWidgets.QLabel(parent=ZoomDialog)
        self.zoomLabel.setObjectName("zoomLabel")
        self.hboxlayout.addWidget(self.zoomLabel)
        self.zoomSpinBox = QtWidgets.QSpinBox(parent=ZoomDialog)
        self.zoomSpinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.zoomSpinBox.setMinimum(-10)
        self.zoomSpinBox.setMaximum(20)
        self.zoomSpinBox.setProperty("value", 0)
        self.zoomSpinBox.setObjectName("zoomSpinBox")
        self.hboxlayout.addWidget(self.zoomSpinBox)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ZoomDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)
        self.zoomLabel.setBuddy(self.zoomSpinBox)

        self.retranslateUi(ZoomDialog)
        self.buttonBox.accepted.connect(ZoomDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ZoomDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ZoomDialog)

    def retranslateUi(self, ZoomDialog):
        _translate = QtCore.QCoreApplication.translate
        ZoomDialog.setWindowTitle(_translate("ZoomDialog", "Zoom"))
        self.zoomLabel.setText(_translate("ZoomDialog", "Zoom &Factor:"))
        self.zoomSpinBox.setToolTip(_translate("ZoomDialog", "Enter zoom factor"))
        self.zoomSpinBox.setWhatsThis(_translate("ZoomDialog", "<b>Zoom Factor</b>\n"
"<p>Enter the desired zoom factor here. The zoom factor\n"
"may be between -10 and +20 and is the increment that is \n"
"added to the size of the fonts used in the editor windows.</p>"))
